services:
  mppi:
    build: .
    network_mode: "host"
    stdin_open: true
    tty: true
    container_name: mppi_benchmark
    cpuset: "0,2,4" #,2,4
    volumes:
      - ./output:/root/nav2_ws/output
    command: ["/bin/bash", "-c", "/root/nav2_ws/entrypoint.sh"]
  